name: molecule test

on:
  pull_request_review:
    types:
      - submitted
  pull_request:
    types:
      - assigned
  schedule:
      - cron: '0 6 * * 0'
  workflow_dispatch:

jobs:
  default:
    name: Test the role
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: "debian11"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible
        uses: MonolithProjects/action-molecule@v1.4.5
        with:
          os: ${{ matrix.config.os }}
          tag: ${{ matrix.config.tag }}
          molecule_command: test
          scenario: default
