name: molecule test

on:
  pull_request_review:
    types:
      - submitted
  pull_request:
    types:
      - assigned
  schedule:
      - cron: '0 6 * * 0'
  workflow_dispatch:

jobs:
  repo:
    name: Test Repo Runner
    environment:
      name: test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: "debian11"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible - GHR Repository
        uses: MonolithProjects/action-molecule@v1.4.5
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          os: ${{ matrix.config.os }}
          tag: ${{ matrix.config.tag }}
          molecule_command: test
          scenario: repo

  org:
    name: Test Org Runner
    environment:
      name: test
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible - GHR Organization
        uses: MonolithProjects/action-molecule@v1.4.5
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          molecule_command: test
          scenario: org
