name: molecule test

on:
  pull_request_review:
    types:
      - submitted
  pull_request:
    types:
      - assigned
  schedule:
      - cron: '0 6 * * 0'
  workflow_dispatch:

jobs:
  test:
    name: Molecule test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: "debian11"
            tag: "latest"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: Molecule for Ansible
        uses: robertdebock/molecule-action@4.0.9
        with:
          os: ${{ matrix.config.os }}
          tag: ${{ matrix.config.tag }}
